### ISSUE TITLE
Bug Report: Converted Files with the Same Name, but Different Extensions Causes One of the Files to Not Be Converted

### ISSUE THREAD

**Issue by Pasqua101** [Yousef-Majidi/Learn2Blog#10]
I didn't notice this when testing my own code, but I discovered that there is an issue where if you have 2 files of the same name but different extension in the same directory (test.txt and test.md in the directory being converted). The output of the first file, test.txt, will be overwritten by the output of test.md. I would suggest to make a helper function that allows for duplicate filenames similar to what Windows has with test.html and test(1).html.

**Comment by Yousef-Majidi** [comment]
thank you for brining it to my attention.

closed by https://github.com/Yousef-Majidi/Learn2Blog/pull/13/commits/8197c77244c8cd216bfab27c605c43110589b6e8
