### ISSUE TITLE
New Feature Proposal: Support for TOML Configuration Files

### ISSUE THREAD

**Issue by mnajibi** [Yousef-Majidi/Learn2Blog#14]
Hi @Yousef-Majidi , I would like to work on your repo to implement a new feature. This feature would allow users to make changes to the program's settings using a special file. Instead of typing out all the settings every time they use the program, users could save their choices in a file named something like "config.toml.

**Comment by Yousef-Majidi** [comment]
@mnajibi Thank you for your contribution. Please provide a preliminary list of changes you want to make, indicating the files you need to modify. 

Also, let me know if you need any clarifications from me.

**Comment by mnajibi** [comment]
@Yousef-Majidi Following our conversation(someone else is gonna work on this feature), I closed the issue.
