### ISSUE TITLE
Clone repository command in readme

### ISSUE THREAD

**Issue by rook4715** [Yousef-Majidi/Learn2Blog#4]
Copying the command ``git clone https://github.com/Yousef-Majidi/learn2blog.Git`` from the readme results in an error:
![image](https://github.com/Yousef-Majidi/Learn2Blog/assets/100863301/e93698b3-98aa-4676-b159-739027d41e5a)

(Just change the uppercase G to a lowercase g)

**Comment by Yousef-Majidi** [comment]
The name of the repository was changed from `lear2blog` to `Learn2Blog` after creation.

fixed in b6eec1a
