### ISSUE TITLE
Title detection

### ISSUE THREAD

**Issue by rook4715** [Yousef-Majidi/Learn2Blog#5]
If no title is parsed, there shouldn't be a title in the output.
From the release 0.1 spec:
"If there is a title, it will be the first line followed by two blank lines."

Input (input.txt):
```
This is paragraph 1.

This is paragraph 2.
```
Expected output:
```
<p>This is paragraph 1.</p>
<p>This is paragraph 2.</p>
```
Output:
```
<h1>input</h1>
<p>This is paragraph 1.</p>
<p>This is paragraph 2.</p>
```

**Comment by Yousef-Majidi** [comment]
fixed in b6eec1a
