### ISSUE TITLE
Cleaning up Code in HtmlProcessor.cs

### ISSUE THREAD

**Issue by Pasqua101** [Yousef-Majidi/Learn2Blog#9]
Some of the code from the ConvertMdToHtml function and from the ConvertTextToHtml function has been reused. Mainly the htmlBuilder code has been reused. I'd suggested cleaning it up by making a function to create the start of the HTML file. 
For example:

``` C#
public static StringBuilder HtmlCreator(title){
    StringBuilder startOfHtml = new();
    startOfHtml.AppendLine("<!DOCTYPE html>")
    // rest of the start of the html file below
    return startOfHtml;
}
```
This doesn't just help cleanup code but also makes modifying the start of the HTML file easier. Since you will only have to make the change in one place.

**Comment by Yousef-Majidi** [comment]
Great suggestion. However, I went a slightly different route. The logic to build the HTML output is moved to a new function, and the processing logic for `.txt` and `.md` files have been broken off into their respective functions. These new functions return the `body` content of the HTML. So, now the input text content is processed based on the file extension and then passed down as an argument to the new function that build the HTML output.

closed by 9b83415
